# Generated by Django 5.0.1 on 2024-01-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Начало заголовка')),
                ('job1', models.CharField(max_length=100, verbose_name='1 Профессия')),
                ('job2', models.CharField(max_length=100, verbose_name='2 Профессия')),
                ('char', models.CharField(max_length=100, verbose_name='Знак')),
                ('title2', models.CharField(max_length=100, verbose_name='Конец заголовка')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Header Info',
            },
        ),
    ]
