# Generated by Django 5.0.1 on 2024-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
