# Generated by Django 5.0.1 on 2024-01-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_header_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступно/Недоступно')),
            ],
            options={
                'verbose_name_plural': 'Main Info',
                'ordering': ('order',),
            },
        ),
    ]
