# Generated by Django 5.0.1 on 2024-01-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_maininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Work Category',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='')),
                ('description', models.TextField(blank=True, verbose_name='')),
                ('photo', models.ImageField(upload_to='main_works_image/', verbose_name='')),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='mainapp.workcategory')),
            ],
            options={
                'verbose_name_plural': 'Works',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('order', 'work_category'), name='unique_work_prt_each_work_category'),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('id', 'slug')},
        ),
    ]
