# Generated by Django 5.0.1 on 2024-01-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_work_unique_together_alter_work_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('id', 'slug')},
        ),
    ]
