# Generated by Django 5.0.1 on 2024-01-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_work_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'Work Categories'},
        ),
    ]
