# Generated by Django 5.0.1 on 2024-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_workcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='char',
            field=models.CharField(blank=True, max_length=100, verbose_name='Знак'),
        ),
        migrations.AlterField(
            model_name='header',
            name='job1',
            field=models.CharField(blank=True, max_length=100, verbose_name='1 Профессия'),
        ),
        migrations.AlterField(
            model_name='header',
            name='job2',
            field=models.CharField(blank=True, max_length=100, verbose_name='2 Профессия'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Конец заголовка'),
        ),
    ]
