# Generated by Django 5.0.1 on 2024-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_header_char_alter_header_job1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='work',
            name='unique_work_prt_each_work_category',
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('order', 'work_category'), name='unique_work_prt_each_main_work_category'),
        ),
    ]
