# Generated by Django 5.0 on 2024-03-20 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='char',
        ),
        migrations.RemoveField(
            model_name='header',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='header',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='title2',
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
