# Generated by Django 5.0 on 2024-03-20 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_workcategory_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='header',
            name='title2',
        ),
        migrations.AddField(
            model_name='header',
            name='title',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
