# Generated by Django 5.0.1 on 2024-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100, verbose_name='')),
                ('title2', models.CharField(blank=True, max_length=100, verbose_name='')),
                ('description', models.TextField(max_length=250, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Contact Header Info',
            },
        ),
    ]
