# Generated by Django 5.0.1 on 2024-01-22 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_app', models.CharField(max_length=100, verbose_name='Почта приложения')),
                ('phone_app', models.CharField(max_length=100, verbose_name='Номер приложения')),
                ('address_app', models.CharField(max_length=100, verbose_name='Адрес')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number should be in format: +380xxxxxxxxx', regex='^\\+?\\d{7,12}$')], verbose_name='Номер телефона')),
                ('subject', models.CharField(max_length=200, verbose_name='Subhect')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Сообщение')),
                ('is_precessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(upload_to='contact/client_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Начало заголовка'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Конец заголовка'),
        ),
    ]
