# Generated by Django 5.0.1 on 2024-01-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contact_address_app_remove_contact_email_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_app', models.CharField(max_length=100, verbose_name='Почта приложения')),
                ('phone_app', models.CharField(max_length=100, verbose_name='Номер приложения')),
                ('address_app', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Info',
            },
        ),
    ]
