# Generated by Django 5.0.1 on 2024-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='header',
            name='head_words',
            field=models.CharField(max_length=200, verbose_name='Главное слово'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Начало заголовка'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title2',
            field=models.CharField(max_length=200, verbose_name='Конец заголовка'),
        ),
    ]
