# Generated by Django 5.0.1 on 2024-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_header_description_alter_header_head_words_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('description', models.TextField(max_length=250, verbose_name='')),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Services Info',
                'ordering': ('order',),
            },
        ),
    ]
