# Generated by Django 5.0.1 on 2024-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('photo', models.ImageField(upload_to='client_images/', verbose_name='')),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступно/Недоступно')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Доступно/Недоступно'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
