# Generated by Django 5.0.1 on 2024-01-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_client_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='link',
        ),
    ]
