# Generated by Django 5.0.1 on 2024-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='head_words',
            field=models.CharField(blank=True, max_length=200, verbose_name='Главное слово'),
        ),
        migrations.AlterField(
            model_name='header',
            name='title2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Конец заголовка'),
        ),
    ]
