# Generated by Django 5.0 on 2024-03-20 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_header_head_words_alter_header_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='head_words',
        ),
        migrations.RemoveField(
            model_name='header',
            name='title2',
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
