# Generated by Django 5.0.1 on 2024-01-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Начало заголовка')),
                ('job1', models.CharField(max_length=100, verbose_name='1 Профессия')),
                ('job2', models.CharField(max_length=100, verbose_name='2 Профессия')),
                ('char', models.CharField(max_length=100, verbose_name='Знак')),
                ('title2', models.CharField(max_length=100, verbose_name='Конец заголовка')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('title3', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('head_words', models.CharField(max_length=100, verbose_name='Главное слово')),
                ('title4', models.CharField(max_length=100, verbose_name='Конец подзаголовка')),
            ],
            options={
                'verbose_name_plural': 'About Header Info',
            },
        ),
    ]
