# Generated by Django 5.0.1 on 2024-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250, verbose_name='')),
                ('photo', models.ImageField(upload_to='client_images/', verbose_name='')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('is_visible', models.BooleanField(default=True, verbose_name='')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ('order',),
            },
        ),
    ]
