# Generated by Django 5.0.1 on 2024-01-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_team_alter_client_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_header_images/', verbose_name='Фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Доступно/Недоступно')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Main About Info',
            },
        ),
    ]
