# Generated by Django 5.0.1 on 2024-01-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_mainaboutinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainAboutInfo',
        ),
    ]
