# Generated by Django 5.0.1 on 2024-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_mainaboutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutheader',
            name='head_words',
            field=models.CharField(blank=True, max_length=100, verbose_name='Главное слово'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='job1',
            field=models.CharField(blank=True, max_length=100, verbose_name='1 Профессия'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='job2',
            field=models.CharField(blank=True, max_length=100, verbose_name='2 Профессия'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Конец заголовка'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='title3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='aboutheader',
            name='title4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Конец подзаголовка'),
        ),
    ]
