# Generated by Django 5.0 on 2024-03-20 12:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutheader_head_words_alter_aboutheader_job1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'About Header Info',
            },
        ),
        migrations.DeleteModel(
            name='AboutHeader',
        ),
    ]
